set_property PACKAGE_PIN W19 [get_ports Clk]
set_property PACKAGE_PIN Y18 [get_ports Reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[1]}]
set_property PACKAGE_PIN M22 [get_ports {Led[0]}]
set_property PACKAGE_PIN N22 [get_ports {Led[1]}]
set_property PACKAGE_PIN M20 [get_ports {Led[2]}]
set_property PACKAGE_PIN N20 [get_ports {Led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property IOSTANDARD LVCMOS33 [get_ports Reset_n]
set_property PACKAGE_PIN L20 [get_ports {Led[7]}]
set_property PACKAGE_PIN L19 [get_ports {Led[6]}]
set_property PACKAGE_PIN L21 [get_ports {Led[5]}]
set_property PACKAGE_PIN M21 [get_ports {Led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[7]}]

set_property CFGBVS VCCO [current_design] 
set_property CONFIG_VOLTAGE 3.3 [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design] 
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design] 
set_property BITSTREAM.CONFIG_MODE SPIx4 [current_design]