set_property SRC_FILE_INFO {cfile:C:/Users/J202-FPGA/Desktop/FPGAProj/led_flash/led_flash.srcs/constrs_1/new/led_flash.xdc rfile:../../../led_flash.srcs/constrs_1/new/led_flash.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports Clk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R16 [get_ports Reset_n]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N20 [get_ports led]
