set_property SRC_FILE_INFO {cfile:C:/Users/J202-FPGA/Desktop/FPGAProj/flip_flop/flip_flop.srcs/constrs_1/new/flip_flop.xdc rfile:../../../flip_flop.srcs/constrs_1/new/flip_flop.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15 [get_ports sys_rst_n]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R16 [get_ports key_in]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N20 [get_ports led_out]
