set_property IOSTANDARD LVCMOS33 [get_ports count]
set_property IOSTANDARD LVCMOS33 [get_ports in_1]
set_property IOSTANDARD LVCMOS33 [get_ports in_2]
set_property IOSTANDARD LVCMOS33 [get_ports sum]
set_property PACKAGE_PIN N20 [get_ports count]
set_property PACKAGE_PIN Y18 [get_ports in_1]
set_property PACKAGE_PIN T20 [get_ports in_2]
set_property PACKAGE_PIN M20 [get_ports sum]

set_property CFGBVS VCCO [current_design] 
set_property CONFIG_VOLTAGE 3.3 [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design] 
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design] 
set_property BITSTREAM.CONFIG_MODE SPIx4 [current_design]